version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  exclusions:
    rules:
      - path: pkg/probe/
        linters:
          - errcheck

formatters:
  enable:
    - gofmt